timeout: 300

email:
  users: 'ci-notifications@foundries.io'

params:
  FACTORY: lmp
  DOCKER_BUILDX: "1"

triggers:
  - name: containers
    type: git_poller
    params:
      GIT_URL: |
        https://github.com/foundriesio/containers.git
      GIT_POLL_REFS: "refs/heads/master"
      OTA_LITE_TAG: postmerge
      DOCKER_COMPOSE_APP: "1"
    runs:
      - name: build-{loop}
        container: foundries/dind-ci:19.03.9_057dbdd
        privileged: true
        loop-on:
          - param: host-tag
            values: [aarch64, armhf, amd64]
        script-repo:
          name: fio
          path: factory-containers/build.sh

    triggers:
      - name: promote-postmerge

  - name: promote-postmerge
    type: simple
    runs:
      - name: publish-apps
        container: foundries/lmp-image-tools
        host-tag: amd64-osf
        privileged: true
        params:
          DOCKER_COMPOSE_APP: "1"
          MANIFEST_PLATFORMS_DEFAULT: linux/amd64,linux/arm64,linux/arm
          OTA_LITE_TAG: postmerge
        script-repo:
          name: fio
          path: factory-containers/publish-containers.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: promote-pr
    type: simple
    runs:
      - name: publish-apps
        container: foundries/lmp-image-tools
        host-tag: amd64-osf
        privileged: true
        params:
          DOCKER_COMPOSE_APP: "1"
          MANIFEST_PLATFORMS_DEFAULT: linux/amd64,linux/arm64,linux/arm
          OTA_LITE_TAG: premerge:postmerge
        script-repo:
          name: fio
          path: factory-containers/publish-containers.sh
        persistent-volumes:
          bitbake: /var/cache/bitbake

  - name: pull-request-containers
    type: github_pr
    runs:
      - name: build-{loop}
        container: foundries/dind-ci:19.03.9_057dbdd
        privileged: true
        params:
          OTA_LITE_TAG: premerge:postmerge
          DOCKER_COMPOSE_APP: "1"
        loop-on:
          - param: host-tag
            values: [aarch64, armhf, amd64]
        script-repo:
          name: fio
          path: factory-containers/build.sh

    triggers:
      - name: promote-pr

script-repos:
  fio:
    clone-url: https://github.com/foundriesio/ci-scripts
